version: "3"
services:
    redis:
      image: redis
      container_name: redis
      restart: always
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
      ports:
        - ${REDIS_HOST_PORT:-6379}:6379
      expose:
        - 6379
      networks:
        - test-net
networks:
  test-net:
    external: true
